language: node_js
env:
  - CXX=g++-4.8
sudo: false
script:
  - npm test
  - npm run lint
  - npm run cover
after_success:
  npm run report
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
